/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { StockInfo, SectorType, SystemSettings } from './types';

/// ข้อมูลหุ้น SET100 ทั้งหมดที่จัดระดับ VI เกรด A
export const INITIAL_STOCKS_DATA: {
  symbol: string;
  name: string;
  dividendYield3Yr: number;
  payoutRatio: number;
  sector: SectorType;
  basePrice: number;
  roe: number;
  deRatio: number;
  fairValue?: number;
  dividendGrowthYears?: number;
  dividendGrowthRate?: number;
  freeCashFlowPositive?: boolean;
  nim?: number;
  npl?: number;
}[] = [
  {
    "symbol": "AAV",
    "name": "เอเชีย แอวิเอชั่น",
    "dividendYield3Yr": 0,
    "payoutRatio": 0,
    "sector": "ขนส่งโลจิสติกส์",
    "basePrice": 2.3,
    "roe": -2.5,
    "deRatio": 3.2,
    "fairValue": 1.8,
    "dividendGrowthYears": 0,
    "dividendGrowthRate": 0,
    "freeCashFlowPositive": false
  },
  {
    "symbol": "ADVANC",
    "name": "แอดวานซ์ อินโฟร์ เซอร์วิส",
    "dividendYield3Yr": 4.15,
    "payoutRatio": 85,
    "sector": "สื่อสาร",
    "basePrice": 210,
    "roe": 32.5,
    "deRatio": 1.8,
    "fairValue": 240,
    "dividendGrowthYears": 5,
    "dividendGrowthRate": 6.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "AEONTS",
    "name": "อิออน ธนสินทรัพย์",
    "dividendYield3Yr": 3.8,
    "payoutRatio": 35,
    "sector": "อื่นๆ",
    "basePrice": 155,
    "roe": 14.2,
    "deRatio": 2.5,
    "fairValue": 180,
    "dividendGrowthYears": 4,
    "dividendGrowthRate": 5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "AMATA",
    "name": "อมตะ คอร์ปอเรชัน",
    "dividendYield3Yr": 2.8,
    "payoutRatio": 40,
    "sector": "อสังหาริมทรัพย์",
    "basePrice": 23.5,
    "roe": 10.5,
    "deRatio": 1.1,
    "fairValue": 26,
    "dividendGrowthYears": 2,
    "dividendGrowthRate": 4,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "AOT",
    "name": "ท่าอากาศยานไทย",
    "dividendYield3Yr": 1.5,
    "payoutRatio": 60,
    "sector": "ขนส่งโลจิสติกส์",
    "basePrice": 61.25,
    "roe": 6.2,
    "deRatio": 1.8,
    "fairValue": 65,
    "dividendGrowthYears": 1,
    "dividendGrowthRate": 2,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "AP",
    "name": "เอพี (ไทยแลนด์)",
    "dividendYield3Yr": 5.8,
    "payoutRatio": 45,
    "sector": "อสังหาริมทรัพย์",
    "basePrice": 10.8,
    "roe": 14.5,
    "deRatio": 0.95,
    "fairValue": 13,
    "dividendGrowthYears": 6,
    "dividendGrowthRate": 5.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "AURA",
    "name": "ออโรร่า ดีไซน์",
    "dividendYield3Yr": 2.5,
    "payoutRatio": 50,
    "sector": "พาณิชย์",
    "basePrice": 14.2,
    "roe": 15.2,
    "deRatio": 1.2,
    "fairValue": 16.5,
    "dividendGrowthYears": 2,
    "dividendGrowthRate": 8,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "AWC",
    "name": "แอสเสท เวิรด์ คอร์ป",
    "dividendYield3Yr": 1.2,
    "payoutRatio": 40,
    "sector": "อสังหาริมทรัพย์",
    "basePrice": 3.68,
    "roe": 3.5,
    "deRatio": 1.5,
    "fairValue": 4.2,
    "dividendGrowthYears": 1,
    "dividendGrowthRate": 1.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "BA",
    "name": "การบินกรุงเทพ",
    "dividendYield3Yr": 2,
    "payoutRatio": 45,
    "sector": "ขนส่งโลจิสติกส์",
    "basePrice": 15.2,
    "roe": 8.5,
    "deRatio": 2.1,
    "fairValue": 14,
    "dividendGrowthYears": 1,
    "dividendGrowthRate": 0,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "BAM",
    "name": "บริหารสินทรัพย์ กรุงเทพพาณิชย์",
    "dividendYield3Yr": 6.5,
    "payoutRatio": 80,
    "sector": "อื่นๆ",
    "basePrice": 8.5,
    "roe": 4.8,
    "deRatio": 1.9,
    "fairValue": 9.5,
    "dividendGrowthYears": 0,
    "dividendGrowthRate": -5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "BANPU",
    "name": "บ้านปู",
    "dividendYield3Yr": 8.3,
    "payoutRatio": 55.4,
    "sector": "พลังงาน",
    "basePrice": 5.4,
    "roe": 5.5,
    "deRatio": 1.8,
    "fairValue": 4.8,
    "dividendGrowthYears": 0,
    "dividendGrowthRate": -2,
    "freeCashFlowPositive": false
  },
  {
    "symbol": "BBL",
    "name": "ธนาคารกรุงเทพ",
    "dividendYield3Yr": 6.4,
    "payoutRatio": 65,
    "sector": "ธนาคาร",
    "basePrice": 138,
    "roe": 8.5,
    "deRatio": 6.8,
    "fairValue": 165,
    "dividendGrowthYears": 3,
    "dividendGrowthRate": 6.2,
    "freeCashFlowPositive": true,
    "nim": 2.8,
    "npl": 2.9
  },
  {
    "symbol": "BCH",
    "name": "บางกอก เชน ฮอสปิทอล",
    "dividendYield3Yr": 3.2,
    "payoutRatio": 60,
    "sector": "อื่นๆ",
    "basePrice": 18.5,
    "roe": 13.8,
    "deRatio": 0.85,
    "fairValue": 21,
    "dividendGrowthYears": 4,
    "dividendGrowthRate": 4.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "BCP",
    "name": "บางจาก คอร์ปอเรชั่น",
    "dividendYield3Yr": 5.5,
    "payoutRatio": 40,
    "sector": "พลังงาน",
    "basePrice": 38,
    "roe": 15.2,
    "deRatio": 1.6,
    "fairValue": 45,
    "dividendGrowthYears": 3,
    "dividendGrowthRate": 8,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "BCPG",
    "name": "บีซีพีจี",
    "dividendYield3Yr": 5.8,
    "payoutRatio": 65,
    "sector": "พลังงาน",
    "basePrice": 6.8,
    "roe": 5.8,
    "deRatio": 1.4,
    "fairValue": 7.5,
    "dividendGrowthYears": 5,
    "dividendGrowthRate": 2,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "BDMS",
    "name": "กรุงเทพดุสิตเวชการ",
    "dividendYield3Yr": 2.8,
    "payoutRatio": 65,
    "sector": "อื่นๆ",
    "basePrice": 28,
    "roe": 14.8,
    "deRatio": 0.35,
    "fairValue": 33,
    "dividendGrowthYears": 6,
    "dividendGrowthRate": 5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "BEM",
    "name": "ทางด่วนและรถไฟฟ้ากรุงเทพ",
    "dividendYield3Yr": 7.4,
    "payoutRatio": 78.5,
    "sector": "ขนส่งโลจิสติกส์",
    "basePrice": 7.65,
    "roe": 8.2,
    "deRatio": 1.7,
    "fairValue": 8.5,
    "dividendGrowthYears": 2,
    "dividendGrowthRate": 3,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "BGRIM",
    "name": "บี.กริม เพาเวอร์",
    "dividendYield3Yr": 2.5,
    "payoutRatio": 45,
    "sector": "พลังงาน",
    "basePrice": 22,
    "roe": 6.8,
    "deRatio": 2.2,
    "fairValue": 25,
    "dividendGrowthYears": 4,
    "dividendGrowthRate": 3.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "BH",
    "name": "โรงพยาบาลบำรุงราษฎร์",
    "dividendYield3Yr": 2.2,
    "payoutRatio": 50,
    "sector": "อื่นๆ",
    "basePrice": 240,
    "roe": 26.5,
    "deRatio": 0.28,
    "fairValue": 280,
    "dividendGrowthYears": 8,
    "dividendGrowthRate": 8.2,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "BJC",
    "name": "เบอร์ลี่ ยุคเกอร์",
    "dividendYield3Yr": 3.5,
    "payoutRatio": 60,
    "sector": "พาณิชย์",
    "basePrice": 25,
    "roe": 4.8,
    "deRatio": 1.4,
    "fairValue": 28.5,
    "dividendGrowthYears": 2,
    "dividendGrowthRate": 1.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "BLA",
    "name": "กรุงเทพประกันชีวิต",
    "dividendYield3Yr": 2.8,
    "payoutRatio": 40,
    "sector": "อื่นๆ",
    "basePrice": 17.5,
    "roe": 6.2,
    "deRatio": 0.15,
    "fairValue": 20,
    "dividendGrowthYears": 1,
    "dividendGrowthRate": -2,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "BTG",
    "name": "เบทาโกร",
    "dividendYield3Yr": 4.5,
    "payoutRatio": 50,
    "sector": "อื่นๆ",
    "basePrice": 21,
    "roe": 5.5,
    "deRatio": 1.3,
    "fairValue": 23,
    "dividendGrowthYears": 1,
    "dividendGrowthRate": 2,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "BTS",
    "name": "บีทีเอส กรุ๊ป โฮลดิ้งส์",
    "dividendYield3Yr": 0,
    "payoutRatio": 0,
    "sector": "ขนส่งโลจิสติกส์",
    "basePrice": 4.8,
    "roe": -4.2,
    "deRatio": 2.8,
    "fairValue": 3.5,
    "dividendGrowthYears": 0,
    "dividendGrowthRate": -10,
    "freeCashFlowPositive": false
  },
  {
    "symbol": "CBG",
    "name": "คาราบาวกรุ๊ป",
    "dividendYield3Yr": 2.8,
    "payoutRatio": 65,
    "sector": "อื่นๆ",
    "basePrice": 68,
    "roe": 14.5,
    "deRatio": 1.15,
    "fairValue": 72,
    "dividendGrowthYears": 3,
    "dividendGrowthRate": 3,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "CCET",
    "name": "แคล-คอมพ์ อีเล็คโทรนิคส์",
    "dividendYield3Yr": 2.2,
    "payoutRatio": 45,
    "sector": "เทคโนโลยี",
    "basePrice": 3.4,
    "roe": 10.8,
    "deRatio": 1.6,
    "fairValue": 3.8,
    "dividendGrowthYears": 1,
    "dividendGrowthRate": 10,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "CENTEL",
    "name": "โรงแรมเซ็นทรัลพลาซา",
    "dividendYield3Yr": 1.8,
    "payoutRatio": 50,
    "sector": "อื่นๆ",
    "basePrice": 36,
    "roe": 5.8,
    "deRatio": 1.8,
    "fairValue": 38,
    "dividendGrowthYears": 1,
    "dividendGrowthRate": 2,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "CHG",
    "name": "โรงพยาบาลจุฬารัตน์",
    "dividendYield3Yr": 4.2,
    "payoutRatio": 80,
    "sector": "อื่นๆ",
    "basePrice": 2.6,
    "roe": 14.2,
    "deRatio": 0.65,
    "fairValue": 3.1,
    "dividendGrowthYears": 5,
    "dividendGrowthRate": 5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "CK",
    "name": "ช.การช่าง",
    "dividendYield3Yr": 2.5,
    "payoutRatio": 45,
    "sector": "อื่นๆ",
    "basePrice": 20.5,
    "roe": 5.2,
    "deRatio": 2.4,
    "fairValue": 23,
    "dividendGrowthYears": 2,
    "dividendGrowthRate": 2.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "COM7",
    "name": "คอมเซเว่น",
    "dividendYield3Yr": 4.2,
    "payoutRatio": 60,
    "sector": "พาณิชย์",
    "basePrice": 18.2,
    "roe": 24.5,
    "deRatio": 0.85,
    "fairValue": 22,
    "dividendGrowthYears": 6,
    "dividendGrowthRate": 12,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "CPALL",
    "name": "ซีพี ออลล์",
    "dividendYield3Yr": 2.5,
    "payoutRatio": 50,
    "sector": "พาณิชย์",
    "basePrice": 57,
    "roe": 16.5,
    "deRatio": 2.1,
    "fairValue": 68,
    "dividendGrowthYears": 5,
    "dividendGrowthRate": 6,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "CPF",
    "name": "เจริญโภคภัณฑ์อาหาร",
    "dividendYield3Yr": 6,
    "payoutRatio": 70,
    "sector": "อื่นๆ",
    "basePrice": 17.8,
    "roe": 4.5,
    "deRatio": 1.9,
    "fairValue": 16,
    "dividendGrowthYears": 1,
    "dividendGrowthRate": 1,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "CPN",
    "name": "เซ็นทรัลพัฒนา",
    "dividendYield3Yr": 2.4,
    "payoutRatio": 40,
    "sector": "อสังหาริมทรัพย์",
    "basePrice": 58,
    "roe": 15.8,
    "deRatio": 1.25,
    "fairValue": 69,
    "dividendGrowthYears": 6,
    "dividendGrowthRate": 5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "CRC",
    "name": "เซ็นทรัล รีเทล คอร์ปอเรชั่น",
    "dividendYield3Yr": 2.2,
    "payoutRatio": 45,
    "sector": "พาณิชย์",
    "basePrice": 32,
    "roe": 8.5,
    "deRatio": 1.6,
    "fairValue": 38,
    "dividendGrowthYears": 2,
    "dividendGrowthRate": 3.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "DELTA",
    "name": "เดลต้า อีเลคโทรนิคส์",
    "dividendYield3Yr": 0.8,
    "payoutRatio": 45,
    "sector": "เทคโนโลยี",
    "basePrice": 74,
    "roe": 28.5,
    "deRatio": 0.45,
    "fairValue": 82,
    "dividendGrowthYears": 5,
    "dividendGrowthRate": 15,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "DOHOME",
    "name": "ดูโฮม",
    "dividendYield3Yr": 1.5,
    "payoutRatio": 40,
    "sector": "พาณิชย์",
    "basePrice": 10.2,
    "roe": 6.2,
    "deRatio": 1.8,
    "fairValue": 11.5,
    "dividendGrowthYears": 1,
    "dividendGrowthRate": 2,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "EA",
    "name": "พลังงานบริสุทธิ์",
    "dividendYield3Yr": 6.6,
    "payoutRatio": 48,
    "sector": "พลังงาน",
    "basePrice": 8.2,
    "roe": 6.8,
    "deRatio": 2.5,
    "fairValue": 6,
    "dividendGrowthYears": 0,
    "dividendGrowthRate": -15,
    "freeCashFlowPositive": false
  },
  {
    "symbol": "EGCO",
    "name": "ผลิตไฟฟ้า (เอ็กโก)",
    "dividendYield3Yr": 6.5,
    "payoutRatio": 79.2,
    "sector": "พลังงาน",
    "basePrice": 108.5,
    "roe": 6.5,
    "deRatio": 1.6,
    "fairValue": 125,
    "dividendGrowthYears": 15,
    "dividendGrowthRate": 2,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "ERW",
    "name": "ดิ เอราวัณ กรุ๊ป",
    "dividendYield3Yr": 1.2,
    "payoutRatio": 40,
    "sector": "อื่นๆ",
    "basePrice": 4.2,
    "roe": 4.8,
    "deRatio": 2.3,
    "fairValue": 4.6,
    "dividendGrowthYears": 1,
    "dividendGrowthRate": 1,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "GFPT",
    "name": "จีเอฟพีที",
    "dividendYield3Yr": 3.5,
    "payoutRatio": 40,
    "sector": "อื่นๆ",
    "basePrice": 11.8,
    "roe": 9.5,
    "deRatio": 0.48,
    "fairValue": 13.5,
    "dividendGrowthYears": 3,
    "dividendGrowthRate": 2.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "GLOBAL",
    "name": "สยามโกลบอลเฮ้าส์",
    "dividendYield3Yr": 2.4,
    "payoutRatio": 45,
    "sector": "พาณิชย์",
    "basePrice": 14.8,
    "roe": 11.2,
    "deRatio": 0.85,
    "fairValue": 16.5,
    "dividendGrowthYears": 4,
    "dividendGrowthRate": 4,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "GPSC",
    "name": "โกลบอล เพาเวอร์ ซินเนอร์ยี่",
    "dividendYield3Yr": 3.2,
    "payoutRatio": 70,
    "sector": "พลังงาน",
    "basePrice": 42.5,
    "roe": 5.8,
    "deRatio": 1.5,
    "fairValue": 48,
    "dividendGrowthYears": 4,
    "dividendGrowthRate": 2.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "GULF",
    "name": "กัลฟ์ เอ็นเนอร์จี ดีเวลลอปเมนท์",
    "dividendYield3Yr": 2.2,
    "payoutRatio": 70,
    "sector": "พลังงาน",
    "basePrice": 40.5,
    "roe": 9.5,
    "deRatio": 1.9,
    "fairValue": 46,
    "dividendGrowthYears": 5,
    "dividendGrowthRate": 8,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "GUNKUL",
    "name": "กันกุลเอ็นจิเนียริ่ง",
    "dividendYield3Yr": 7.6,
    "payoutRatio": 75.1,
    "sector": "พลังงาน",
    "basePrice": 2.72,
    "roe": 12.5,
    "deRatio": 1.5,
    "fairValue": 3.2,
    "dividendGrowthYears": 6,
    "dividendGrowthRate": 5.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "HANA",
    "name": "ฮานา ไมโครอิเล็คโทรนิคส",
    "dividendYield3Yr": 4.5,
    "payoutRatio": 60,
    "sector": "เทคโนโลยี",
    "basePrice": 36,
    "roe": 8.2,
    "deRatio": 0.38,
    "fairValue": 42,
    "dividendGrowthYears": 4,
    "dividendGrowthRate": 3,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "HMPRO",
    "name": "โฮม โปรดักส์ เซ็นเตอร์",
    "dividendYield3Yr": 6,
    "payoutRatio": 79,
    "sector": "พาณิชย์",
    "basePrice": 9.8,
    "roe": 24.5,
    "deRatio": 0.95,
    "fairValue": 12,
    "dividendGrowthYears": 10,
    "dividendGrowthRate": 4.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "ICHI",
    "name": "อิชิตัน กรุ๊ป",
    "dividendYield3Yr": 6.5,
    "payoutRatio": 75,
    "sector": "อื่นๆ",
    "basePrice": 16.2,
    "roe": 18.2,
    "deRatio": 0.25,
    "fairValue": 19,
    "dividendGrowthYears": 4,
    "dividendGrowthRate": 12,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "IRPC",
    "name": "ไออาร์พีซี",
    "dividendYield3Yr": 5.2,
    "payoutRatio": 60,
    "sector": "พลังงาน",
    "basePrice": 1.8,
    "roe": 2.5,
    "deRatio": 1.45,
    "fairValue": 1.6,
    "dividendGrowthYears": 0,
    "dividendGrowthRate": -8,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "IVL",
    "name": "อินโดรามา เวนเจอร์ส",
    "dividendYield3Yr": 4,
    "payoutRatio": 45,
    "sector": "อื่นๆ",
    "basePrice": 24,
    "roe": 5.2,
    "deRatio": 1.6,
    "fairValue": 21,
    "dividendGrowthYears": 1,
    "dividendGrowthRate": -5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "JAS",
    "name": "จัสมิน อินเตอร์เนชั่นแนล",
    "dividendYield3Yr": 0,
    "payoutRatio": 0,
    "sector": "สื่อสาร",
    "basePrice": 2.1,
    "roe": -8.5,
    "deRatio": 4.2,
    "fairValue": 1.5,
    "dividendGrowthYears": 0,
    "dividendGrowthRate": 0,
    "freeCashFlowPositive": false
  },
  {
    "symbol": "JMART",
    "name": "เจ มาร์ท กรุ๊ป",
    "dividendYield3Yr": 2.8,
    "payoutRatio": 55,
    "sector": "พาณิชย์",
    "basePrice": 14.5,
    "roe": 6.5,
    "deRatio": 1.8,
    "fairValue": 13,
    "dividendGrowthYears": 2,
    "dividendGrowthRate": -2,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "JMT",
    "name": "เจ เอ็ม ที เน็ทเวอร์ค เซอร์วิส",
    "dividendYield3Yr": 4.2,
    "payoutRatio": 60,
    "sector": "อื่นๆ",
    "basePrice": 20.2,
    "roe": 14.2,
    "deRatio": 1.2,
    "fairValue": 24.5,
    "dividendGrowthYears": 4,
    "dividendGrowthRate": 8,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "JTS",
    "name": "จัสมิน เทคโนโลยี โซลูชั่น",
    "dividendYield3Yr": 0.5,
    "payoutRatio": 20,
    "sector": "เทคโนโลยี",
    "basePrice": 68,
    "roe": 18.5,
    "deRatio": 2.2,
    "fairValue": 45,
    "dividendGrowthYears": 1,
    "dividendGrowthRate": 15,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "KBANK",
    "name": "ธนาคารกสิกรไทย",
    "dividendYield3Yr": 4.5,
    "payoutRatio": 35,
    "sector": "ธนาคาร",
    "basePrice": 122.5,
    "roe": 9.2,
    "deRatio": 7.1,
    "fairValue": 145,
    "dividendGrowthYears": 4,
    "dividendGrowthRate": 5,
    "freeCashFlowPositive": true,
    "nim": 3.3,
    "npl": 3.8
  },
  {
    "symbol": "KCE",
    "name": "เคซีอี อีเลคโทรนิคส์",
    "dividendYield3Yr": 3.8,
    "payoutRatio": 65,
    "sector": "เทคโนโลยี",
    "basePrice": 38.5,
    "roe": 14.8,
    "deRatio": 0.55,
    "fairValue": 44,
    "dividendGrowthYears": 5,
    "dividendGrowthRate": 4.2,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "KKP",
    "name": "ธนาคารเกียรตินาคินภัทร",
    "dividendYield3Yr": 6.2,
    "payoutRatio": 55,
    "sector": "ธนาคาร",
    "basePrice": 48,
    "roe": 11.2,
    "deRatio": 8.2,
    "fairValue": 58,
    "dividendGrowthYears": 8,
    "dividendGrowthRate": 5.5,
    "freeCashFlowPositive": true,
    "nim": 3.1,
    "npl": 3.2
  },
  {
    "symbol": "KTB",
    "name": "ธนาคารกรุงไทย",
    "dividendYield3Yr": 6.8,
    "payoutRatio": 68.2,
    "sector": "ธนาคาร",
    "basePrice": 18.5,
    "roe": 10.2,
    "deRatio": 7.1,
    "fairValue": 22,
    "dividendGrowthYears": 5,
    "dividendGrowthRate": 7.8,
    "freeCashFlowPositive": true,
    "nim": 3.2,
    "npl": 3.1
  },
  {
    "symbol": "KTC",
    "name": "บัตรกรุงไทย",
    "dividendYield3Yr": 3.2,
    "payoutRatio": 45,
    "sector": "อื่นๆ",
    "basePrice": 44.25,
    "roe": 18.5,
    "deRatio": 2.4,
    "fairValue": 52,
    "dividendGrowthYears": 6,
    "dividendGrowthRate": 7.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "LH",
    "name": "แลนด์แอนด์เฮ้าส์",
    "dividendYield3Yr": 6.4,
    "payoutRatio": 79.5,
    "sector": "อสังหาริมทรัพย์",
    "basePrice": 6.25,
    "roe": 12.2,
    "deRatio": 1.15,
    "fairValue": 7.2,
    "dividendGrowthYears": 5,
    "dividendGrowthRate": 2,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "M",
    "name": "เอ็มเค เรสโตรองต์ กรุ๊ป",
    "dividendYield3Yr": 4.8,
    "payoutRatio": 85,
    "sector": "อื่นๆ",
    "basePrice": 34,
    "roe": 8.5,
    "deRatio": 0.35,
    "fairValue": 38,
    "dividendGrowthYears": 10,
    "dividendGrowthRate": 1.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "MEGA",
    "name": "เมก้า ไลฟ์ไซแอ็นซ์",
    "dividendYield3Yr": 4.1,
    "payoutRatio": 50,
    "sector": "อื่นๆ",
    "basePrice": 38.25,
    "roe": 18.5,
    "deRatio": 0.18,
    "fairValue": 44,
    "dividendGrowthYears": 5,
    "dividendGrowthRate": 8.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "MINT",
    "name": "ไมเนอร์ อินเตอร์เนชั่นแนล",
    "dividendYield3Yr": 6.3,
    "payoutRatio": 58,
    "sector": "อื่นๆ",
    "basePrice": 26.5,
    "roe": 9.5,
    "deRatio": 1.8,
    "fairValue": 30,
    "dividendGrowthYears": 1,
    "dividendGrowthRate": 2.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "MOSHI",
    "name": "โมชิ โมชิ",
    "dividendYield3Yr": 2.2,
    "payoutRatio": 45,
    "sector": "พาณิชย์",
    "basePrice": 48,
    "roe": 18.2,
    "deRatio": 0.45,
    "fairValue": 55,
    "dividendGrowthYears": 2,
    "dividendGrowthRate": 10,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "MTC",
    "name": "เมืองไทย แคปปิตอล",
    "dividendYield3Yr": 2.5,
    "payoutRatio": 25,
    "sector": "อื่นๆ",
    "basePrice": 42,
    "roe": 16.5,
    "deRatio": 3.5,
    "fairValue": 48,
    "dividendGrowthYears": 6,
    "dividendGrowthRate": 8,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "OR",
    "name": "ปตท. น้ำมันและการค้าปลีก",
    "dividendYield3Yr": 3.8,
    "payoutRatio": 50,
    "sector": "พลังงาน",
    "basePrice": 16.5,
    "roe": 7.2,
    "deRatio": 0.85,
    "fairValue": 19.5,
    "dividendGrowthYears": 3,
    "dividendGrowthRate": 3,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "OSP",
    "name": "โอสถสภา",
    "dividendYield3Yr": 4.5,
    "payoutRatio": 80,
    "sector": "อื่นๆ",
    "basePrice": 21,
    "roe": 12.8,
    "deRatio": 0.95,
    "fairValue": 24,
    "dividendGrowthYears": 5,
    "dividendGrowthRate": 4,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "PLANB",
    "name": "แพลน บี มีเดีย",
    "dividendYield3Yr": 2.4,
    "payoutRatio": 60,
    "sector": "อื่นๆ",
    "basePrice": 8.2,
    "roe": 9.5,
    "deRatio": 0.85,
    "fairValue": 9.2,
    "dividendGrowthYears": 3,
    "dividendGrowthRate": 5.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "PR9",
    "name": "โรงพยาบาลพระรามเก้า",
    "dividendYield3Yr": 3.8,
    "payoutRatio": 65,
    "sector": "อื่นๆ",
    "basePrice": 16.8,
    "roe": 12.8,
    "deRatio": 0.22,
    "fairValue": 20,
    "dividendGrowthYears": 4,
    "dividendGrowthRate": 8,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "PRM",
    "name": "พริมา มารีน",
    "dividendYield3Yr": 4.5,
    "payoutRatio": 45,
    "sector": "ขนส่งโลจิสติกส์",
    "basePrice": 7.8,
    "roe": 15.2,
    "deRatio": 0.85,
    "fairValue": 9.5,
    "dividendGrowthYears": 5,
    "dividendGrowthRate": 6,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "PTG",
    "name": "พีทีจี เอ็นเนอยี",
    "dividendYield3Yr": 5.2,
    "payoutRatio": 60,
    "sector": "พลังงาน",
    "basePrice": 8.8,
    "roe": 7.8,
    "deRatio": 2.1,
    "fairValue": 10,
    "dividendGrowthYears": 3,
    "dividendGrowthRate": 2,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "PTT",
    "name": "ปตท.",
    "dividendYield3Yr": 5.25,
    "payoutRatio": 48.5,
    "sector": "พลังงาน",
    "basePrice": 32.25,
    "roe": 9.5,
    "deRatio": 0.95,
    "fairValue": 38,
    "dividendGrowthYears": 10,
    "dividendGrowthRate": 4.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "PTTEP",
    "name": "ปตท.สำรวจและผลิตปิโตรเลียม",
    "dividendYield3Yr": 6.7,
    "payoutRatio": 70,
    "sector": "พลังงาน",
    "basePrice": 142.5,
    "roe": 14.8,
    "deRatio": 0.3,
    "fairValue": 160,
    "dividendGrowthYears": 8,
    "dividendGrowthRate": 7,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "PTTGC",
    "name": "พีทีที โกลบอล เคมิคอล",
    "dividendYield3Yr": 3.5,
    "payoutRatio": 50,
    "sector": "พลังงาน",
    "basePrice": 36,
    "roe": 2.5,
    "deRatio": 1.1,
    "fairValue": 32,
    "dividendGrowthYears": 0,
    "dividendGrowthRate": -10,
    "freeCashFlowPositive": false
  },
  {
    "symbol": "QH",
    "name": "ควอลิตี้เฮ้าส์",
    "dividendYield3Yr": 6.8,
    "payoutRatio": 80,
    "sector": "อสังหาริมทรัพย์",
    "basePrice": 2.15,
    "roe": 8.2,
    "deRatio": 0.85,
    "fairValue": 2.45,
    "dividendGrowthYears": 5,
    "dividendGrowthRate": 1.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "RATCH",
    "name": "ราช กรุ๊ป",
    "dividendYield3Yr": 7.2,
    "payoutRatio": 76.5,
    "sector": "พลังงาน",
    "basePrice": 31.25,
    "roe": 7.8,
    "deRatio": 1.2,
    "fairValue": 35,
    "dividendGrowthYears": 12,
    "dividendGrowthRate": 1.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "RCL",
    "name": "อาร์ ซี แอล",
    "dividendYield3Yr": 6.5,
    "payoutRatio": 40,
    "sector": "ขนส่งโลจิสติกส์",
    "basePrice": 22,
    "roe": 6.8,
    "deRatio": 0.65,
    "fairValue": 20,
    "dividendGrowthYears": 1,
    "dividendGrowthRate": -15,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "SAWAD",
    "name": "ศรีสวัสดิ์ คอร์ปอเรชั่น",
    "dividendYield3Yr": 5.8,
    "payoutRatio": 50,
    "sector": "อื่นๆ",
    "basePrice": 38,
    "roe": 15.8,
    "deRatio": 2.8,
    "fairValue": 44,
    "dividendGrowthYears": 5,
    "dividendGrowthRate": 5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "SCB",
    "name": "เอสซีบี เอกซ์",
    "dividendYield3Yr": 7.1,
    "payoutRatio": 72.5,
    "sector": "ธนาคาร",
    "basePrice": 112.5,
    "roe": 10.5,
    "deRatio": 7.5,
    "fairValue": 130,
    "dividendGrowthYears": 4,
    "dividendGrowthRate": 8.5,
    "freeCashFlowPositive": true,
    "nim": 3.5,
    "npl": 3.3
  },
  {
    "symbol": "SCC",
    "name": "ปูนซิเมนต์ไทย",
    "dividendYield3Yr": 3.5,
    "payoutRatio": 55,
    "sector": "อื่นๆ",
    "basePrice": 250,
    "roe": 6.2,
    "deRatio": 1.25,
    "fairValue": 275,
    "dividendGrowthYears": 10,
    "dividendGrowthRate": 1,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "SCGP",
    "name": "เอสซีจี แพคเกจจิ้ง",
    "dividendYield3Yr": 3.2,
    "payoutRatio": 50,
    "sector": "อื่นๆ",
    "basePrice": 34,
    "roe": 5.8,
    "deRatio": 0.95,
    "fairValue": 38,
    "dividendGrowthYears": 3,
    "dividendGrowthRate": 2.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "SIRI",
    "name": "แสนสิริ",
    "dividendYield3Yr": 7.8,
    "payoutRatio": 50,
    "sector": "อสังหาริมทรัพย์",
    "basePrice": 1.85,
    "roe": 15.5,
    "deRatio": 1.6,
    "fairValue": 2.2,
    "dividendGrowthYears": 4,
    "dividendGrowthRate": 8,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "SISB",
    "name": "เอสไอเอสบี",
    "dividendYield3Yr": 1.8,
    "payoutRatio": 50,
    "sector": "อื่นๆ",
    "basePrice": 36,
    "roe": 24.5,
    "deRatio": 0.18,
    "fairValue": 42,
    "dividendGrowthYears": 4,
    "dividendGrowthRate": 15,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "SJWD",
    "name": "เอสซีจี เจดับเบิ้ลยูดี โลจิสติกส์",
    "dividendYield3Yr": 3,
    "payoutRatio": 55,
    "sector": "ขนส่งโลจิสติกส์",
    "basePrice": 12,
    "roe": 6.5,
    "deRatio": 1.45,
    "fairValue": 13.5,
    "dividendGrowthYears": 2,
    "dividendGrowthRate": 3,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "SPALI",
    "name": "ศุภาลัย",
    "dividendYield3Yr": 6.2,
    "payoutRatio": 40.5,
    "sector": "อสังหาริมทรัพย์",
    "basePrice": 19.5,
    "roe": 13.8,
    "deRatio": 0.68,
    "fairValue": 23,
    "dividendGrowthYears": 5,
    "dividendGrowthRate": 3.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "SPRC",
    "name": "สตาร์ ปิโตรเลียม รีไฟน์นิ่ง",
    "dividendYield3Yr": 5.5,
    "payoutRatio": 60,
    "sector": "พลังงาน",
    "basePrice": 8.2,
    "roe": 4.8,
    "deRatio": 0.85,
    "fairValue": 9,
    "dividendGrowthYears": 2,
    "dividendGrowthRate": -2,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "STA",
    "name": "ศรีตรังแอโกรอินดัสทรี",
    "dividendYield3Yr": 5.2,
    "payoutRatio": 55,
    "sector": "อื่นๆ",
    "basePrice": 18.2,
    "roe": 5.8,
    "deRatio": 0.85,
    "fairValue": 20,
    "dividendGrowthYears": 1,
    "dividendGrowthRate": -5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "STECON",
    "name": "สเตคอน กรุ๊ป",
    "dividendYield3Yr": 2.8,
    "payoutRatio": 50,
    "sector": "อื่นๆ",
    "basePrice": 9.2,
    "roe": 4.2,
    "deRatio": 1.25,
    "fairValue": 10.5,
    "dividendGrowthYears": 2,
    "dividendGrowthRate": 1,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "STGT",
    "name": "ศรีตรังโกลฟส์ (ประเทศไทย)",
    "dividendYield3Yr": 6.8,
    "payoutRatio": 72,
    "sector": "อื่นๆ",
    "basePrice": 7.4,
    "roe": 5.2,
    "deRatio": 0.6,
    "fairValue": 6.8,
    "dividendGrowthYears": 0,
    "dividendGrowthRate": -8,
    "freeCashFlowPositive": false
  },
  {
    "symbol": "TASCO",
    "name": "ทิปโก้แอสฟัลท์",
    "dividendYield3Yr": 6.2,
    "payoutRatio": 75,
    "sector": "อื่นๆ",
    "basePrice": 16.8,
    "roe": 12.5,
    "deRatio": 0.58,
    "fairValue": 19,
    "dividendGrowthYears": 5,
    "dividendGrowthRate": 3.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "TCAP",
    "name": "ทุนธนชาต",
    "dividendYield3Yr": 6.8,
    "payoutRatio": 65,
    "sector": "ธนาคาร",
    "basePrice": 50,
    "roe": 10.8,
    "deRatio": 1.15,
    "fairValue": 58,
    "dividendGrowthYears": 10,
    "dividendGrowthRate": 4.8,
    "freeCashFlowPositive": true,
    "nim": 3,
    "npl": 2.8
  },
  {
    "symbol": "TFG",
    "name": "ไทยฟู้ดส์ กรุ๊ป",
    "dividendYield3Yr": 3.8,
    "payoutRatio": 50,
    "sector": "อื่นๆ",
    "basePrice": 3.85,
    "roe": 6.8,
    "deRatio": 1.95,
    "fairValue": 4.3,
    "dividendGrowthYears": 2,
    "dividendGrowthRate": 3,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "TIDLOR",
    "name": "เงินติดล้อ",
    "dividendYield3Yr": 2.8,
    "payoutRatio": 35,
    "sector": "อื่นๆ",
    "basePrice": 21,
    "roe": 12.5,
    "deRatio": 2.6,
    "fairValue": 25,
    "dividendGrowthYears": 3,
    "dividendGrowthRate": 8,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "TISCO",
    "name": "ทิสโก้ไฟแนนเชียลกรุ๊ป",
    "dividendYield3Yr": 7.8,
    "payoutRatio": 85,
    "sector": "ธนาคาร",
    "basePrice": 98,
    "roe": 17.5,
    "deRatio": 1.35,
    "fairValue": 108,
    "dividendGrowthYears": 12,
    "dividendGrowthRate": 5.5,
    "freeCashFlowPositive": true,
    "nim": 4.8,
    "npl": 2.2
  },
  {
    "symbol": "TLI",
    "name": "ไทยประกันชีวิต",
    "dividendYield3Yr": 7,
    "payoutRatio": 64,
    "sector": "อื่นๆ",
    "basePrice": 8.85,
    "roe": 9.1,
    "deRatio": 4.8,
    "fairValue": 10.5,
    "dividendGrowthYears": 2,
    "dividendGrowthRate": 3,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "TOA",
    "name": "ทีโอเอ เพ้นท์",
    "dividendYield3Yr": 3.1,
    "payoutRatio": 50,
    "sector": "อื่นๆ",
    "basePrice": 21.5,
    "roe": 11.2,
    "deRatio": 0.35,
    "fairValue": 24.5,
    "dividendGrowthYears": 4,
    "dividendGrowthRate": 4,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "TOP",
    "name": "ไทยออยล์",
    "dividendYield3Yr": 5.8,
    "payoutRatio": 40,
    "sector": "พลังงาน",
    "basePrice": 52,
    "roe": 12.8,
    "deRatio": 1.45,
    "fairValue": 60,
    "dividendGrowthYears": 5,
    "dividendGrowthRate": 5.5,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "TRUE",
    "name": "ทรู คอร์ปอเรชั่น",
    "dividendYield3Yr": 6.2,
    "payoutRatio": 76,
    "sector": "สื่อสาร",
    "basePrice": 7.95,
    "roe": -2.5,
    "deRatio": 3.8,
    "fairValue": 6.5,
    "dividendGrowthYears": 0,
    "dividendGrowthRate": 0,
    "freeCashFlowPositive": false
  },
  {
    "symbol": "TTB",
    "name": "ธนาคารทหารไทยธนชาต",
    "dividendYield3Yr": 6.2,
    "payoutRatio": 78,
    "sector": "ธนาคาร",
    "basePrice": 1.78,
    "roe": 8.8,
    "deRatio": 7.3,
    "fairValue": 2.1,
    "dividendGrowthYears": 4,
    "dividendGrowthRate": 9.2,
    "freeCashFlowPositive": true,
    "nim": 2.6,
    "npl": 2.7
  },
  {
    "symbol": "TU",
    "name": "ไทยยูเนี่ยน กรุ๊ป",
    "dividendYield3Yr": 5.1,
    "payoutRatio": 55,
    "sector": "อื่นๆ",
    "basePrice": 14.8,
    "roe": 9.5,
    "deRatio": 1.25,
    "fairValue": 17,
    "dividendGrowthYears": 8,
    "dividendGrowthRate": 3,
    "freeCashFlowPositive": true
  },
  {
    "symbol": "VGI",
    "name": "วีจีไอ",
    "dividendYield3Yr": 0,
    "payoutRatio": 0,
    "sector": "อื่นๆ",
    "basePrice": 1.65,
    "roe": -5.8,
    "deRatio": 1.15,
    "fairValue": 1.2,
    "dividendGrowthYears": 0,
    "dividendGrowthRate": -15,
    "freeCashFlowPositive": false
  },
  {
    "symbol": "WHA",
    "name": "ดับบลิวเอชเอ คอร์ปอเรชั่น",
    "dividendYield3Yr": 6.1,
    "payoutRatio": 74,
    "sector": "อสังหาริมทรัพย์",
    "basePrice": 5.15,
    "roe": 15.5,
    "deRatio": 1.3,
    "fairValue": 5.8,
    "dividendGrowthYears": 3,
    "dividendGrowthRate": 6.5,
    "freeCashFlowPositive": true
  }
];


export function generateHistoricalPrices(symbol: string, basePrice: number): number[] {
  const count = 75; // จำนวนราคาย้อนหลัง
  const prices: number[] = [];
  let current = basePrice;
  
  // สุ่มเมล็ดพันธุ์คงที่ตามชื่อย่อหุ้น เพื่อให้หน้าตาราคาเป็นมิตรและเป็นระบบ
  let seed = 0;
  for (let i = 0; i < symbol.length; i++) {
    seed += symbol.charCodeAt(i);
  }
  
  const pseudoRandom = () => {
    const x = Math.sin(seed++) * 10000;
    return x - Math.floor(x);
  };

  // กำหนดแนวโน้มเฉพาะหุ้นบางกลุ่ม เพื่อจำลองสภาวะตลาด
  // บางตัวลงต่อเนื่อง (Oversold), บางตัวขึ้นต่อเนื่อง (Overbought) เพื่อเป็นตัวอย่างในหน้าแท็บ 1
  let bias = 0;
  if (['SCB', 'GUNKUL', 'LH'].includes(symbol)) {
    bias = -0.003; // มีแนวโน้มปรับฐานลงแรง (มีโอกาสเกิด RSI ต่ำกว่า 20)
  } else if (['BBL', 'PTTEP', 'STGT'].includes(symbol)) {
    bias = 0.0045; // ขาขึ้นแรง (มีโอกาสเกิด RSI สูงกว่า 80)
  }

  // สร้างประวัติราคา
  for (let i = 0; i < count; i++) {
    const change = (pseudoRandom() - 0.495 + bias) * 0.024; // สุ่มแกว่ง +-2.4% + ชดเชยแนวโน้ม
    current = current * (1 + change);
    prices.push(Number(current.toFixed(2)));
  }
  
  // จัดเรียงแบบเก่าสุดไปใหม่สุด (ล่าสุดจะอยู่ท้ายอาร์เรย์)
  return prices;
}

// ค่าตั้งต้นสำหรับ SystemSettings
export const DEFAULT_SETTINGS: SystemSettings = {
  totalCapital: 5000000,        // ทุนรวมเริ่มต้น 5,000,000 บาท
  rsiBuyThreshold: 20,          // RSI < 20 เพื่อรับซื้อ
  rsiSellThreshold: 80,         // RSI > 80 เพื่อเทขายทำกำไร
  tranche1Percent: 15,          // ไม้ 1 = 15%
  tranche2Percent: 20,          // ไม้ 2 = 20%
  tranche3Percent: 28,          // ไม้ 3 = 28%
  tranche4Percent: 37,          // ไม้ 4 = 37%
  tranche2Gap: 7,               // ลดลง >= 7% จากไม้ 1
  tranche3Gap: 8,               // ลดลง >= 8% จากไม้ 2
  tranche4Gap: 9,               // ลดลง >= 9% จากไม้ 3
  stopLossPercent: 30,          // คัดลอสที่ -30% จากราคาไม้ 1
  trailingStopPercent: 8,       // ย่อจากจุดสูงสุด 8% เพื่อขาย 50% ที่เหลือ
  sma60WarningGap: 15,          // ห้ามซื้อไม้ 4 หากต่ำกว่า SMA60 เกิน 15%
  brokerFeePercent: 0.155,      // ค่าธรรมเนียม Standard SET 0.155%
  vatPercent: 7,                 // VAT 7%
  timeframe: 'D1',              // ไทม์เฟรมเริ่มต้น (รายวัน)
  enableWebNotifications: false, // ระบบแจ้งเตือนบราวเซอร์เริ่มต้นปิดอยู่
  notificationCheckInterval: 5,  // ตรวจสอบข้อมูลหุ้นทุกๆ 5 นาทีเป็นค่าเริ่มต้น
  requireMOSPercent: 20,         // เกณฑ์ Margin of Safety ขั้นต่ำเริ่มต้นที่ 20%
  bennerCashAllocation: true     // เปิดใช้งานระบบวิเคราะห์จัดสรรเงินสดสะสมตามรอบวัฏจักร Benner
};
